# Generated by Django 6.0.3 on 2026-03-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users with admin-level access to this org (set by the Institution Superuser)', related_name='org_admin_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital allocated from the main Org budget to this project', max_digits=12),
        ),
        migrations.AlterField(
            model_name='capitalrequest',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orgs.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('superuser', models.OneToOneField(blank=True, help_text='The single superuser account for this institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superuser_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='orgs.institution'),
        ),
    ]
