# Generated by Django 6.0.3 on 2026-03-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organization_admins_project_allocated_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allocated_budget',
        ),
    ]
