# Generated by Django 6.0.3 on 2026-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_creditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalrequest',
            name='category',
            field=models.CharField(choices=[('EVENTS', 'Events & Programming'), ('TRAVEL', 'Travel'), ('OPERATIONS', 'Operations'), ('MARKETING', 'Marketing & Outreach'), ('PERSONNEL', 'Personnel'), ('FUNDRAISING', 'Fundraising'), ('EQUIPMENT', 'Equipment'), ('MISC', 'Miscellaneous')], default='MISC', max_length=50),
        ),
        migrations.AddField(
            model_name='creditevent',
            name='source',
            field=models.CharField(choices=[('STUDENT_FEES', 'Student Activity Fees'), ('DUES', 'Member Dues'), ('FUNDRAISING', 'Fundraising Revenue'), ('DONATION', 'Donation / Grant'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
